import streamlit as st
import requests
import json
import os

st.set_page_config(page_title="RockyCAD", layout="wide", initial_sidebar_state="expanded")

HISTORY_FILE = "rockycad_history.json"

def load_state():
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE, "r") as f:
                return json.load(f)
        except:
            pass
    return {
        "messages": [{"role": "assistant", "content": "Welcome to RockyCAD. Describe the 3D model you want to generate."}],
        "current_code": "// Your active OpenSCAD code will appear here"
    }

def save_state():
    with open(HISTORY_FILE, "w") as f:
        json.dump({
            "messages": st.session_state.messages,
            "current_code": st.session_state.current_code
        }, f)

# Initialize session state from file
if "messages" not in st.session_state:
    saved_data = load_state()
    st.session_state.messages = saved_data["messages"]
    st.session_state.current_code = saved_data["current_code"]

def update_sidebar_code():
    st.session_state.current_code = st.session_state.sidebar_editor
    save_state()
    
# --- LEFT SIDEBAR (Options & Compiler) ---
with st.sidebar:
    st.title("⚙️ Workspace")
    st.caption("Model: nemotron-3-super-120b-a12b")
    st.divider()
    
    st.subheader("Active Code Console")
    # This allows you to edit the code generated by the chat before compiling
    edited_code = st.text_area(
        "Review / Edit OpenSCAD:", 
        value=st.session_state.current_code, 
        height=350,
        key="sidebar_editor",
        on_change=update_sidebar_code,
        help="Make manual dimension tweaks here before compiling."
    )
    
    if st.button("Compile to 3D (.stl)", use_container_width=True):
        if edited_code and edited_code.strip() != "// Your active OpenSCAD code will appear here":
            with st.spinner("Compiling via OpenSCAD..."):
                try:
                    res = requests.post(
                        "http://127.0.0.1:8000/api/compile", 
                        json={"scad_code": edited_code}
                    )
                    if res.status_code == 200:
                        st.download_button(
                            label="⬇️ Download model.stl",
                            data=res.content,
                            file_name="rockycad_model.stl",
                            mime="application/sla",
                            use_container_width=True
                        )
                        st.success("Compilation successful!")
                    else:
                        st.error(f"Compiler Error: {res.text}")
                except Exception as e:
                    st.error(f"FastAPI Connection Error: {e}")

# --- MAIN CENTER CHAT INTERFACE ---
st.title("RockyCAD Studio")

# --- MAIN CENTER CHAT INTERFACE ---
st.title("RockyCAD Studio")

# Catch prompts that are triggered by the "Resend" button
if "resend_prompt" not in st.session_state:
    st.session_state.resend_prompt = None

# Render previous chat history
for i, message in enumerate(st.session_state.messages):
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            # Check if this specific message is in edit mode
            if st.session_state.get(f"editing_{i}", False):
                new_text = st.text_area("Edit your prompt:", value=message["content"], key=f"area_{i}", label_visibility="collapsed")
                btn_col1, btn_col2, _ = st.columns([1, 1, 8])
                with btn_col1:
                    if st.button("Cancel", key=f"cancel_{i}"):
                        st.session_state[f"editing_{i}"] = False
                        st.rerun()
                with btn_col2:
                    if st.button("Resend", type="primary", key=f"resend_{i}"):
                        st.session_state[f"editing_{i}"] = False
                        st.session_state.resend_prompt = new_text
                        st.rerun()
            else:
                # Display as normal plain text
                st.markdown(message["content"])
                # Sleek, borderless tertiary button underneath the prompt
                if st.button("✏️ Edit", key=f"edit_btn_{i}", type="tertiary"):
                    st.session_state[f"editing_{i}"] = True
                    st.rerun()
        else:
            st.markdown(message["content"])

# The prompt comes either from the bottom chat bar OR from a clicked Resend button
chat_val = st.chat_input("Describe your 3D component (e.g., A 20x20mm cube with a 5mm hole...)")
active_prompt = chat_val or st.session_state.resend_prompt

if active_prompt:
    # Clear the resend trigger so it only fires once
    if st.session_state.resend_prompt:
        st.session_state.resend_prompt = None
        
    # 1. Add user prompt to screen and memory
    st.session_state.messages.append({"role": "user", "content": active_prompt})
    save_state()
    with st.chat_message("user"):
        st.markdown(active_prompt)
        
    # 2. Call FastAPI and stream response
    with st.chat_message("assistant"):
        with st.spinner("Generating CAD..."):
            try:
                res = requests.post(
                    "http://127.0.0.1:8000/api/generate", 
                    json={"prompt": active_prompt, "model": "nvidia/nemotron-3-super-120b-a12b"}
                )
                if res.status_code == 200:
                    code = res.json().get("scad_code", "")
                    
                    # Update sidebar with the new code
                    st.session_state.current_code = code
                    
                    # Display code in the chat stream
                    formatted_response = f"Here is the geometry for your request:\n```openscad\n{code}\n```"
                    st.markdown(formatted_response)
                    st.session_state.messages.append({"role": "assistant", "content": formatted_response})
                    
                    # Save state permanently to JSON file
                    save_state()
                    
                    # Force UI refresh to update the sidebar editor
                    st.rerun()
                else:
                    st.error(f"Backend Error: {res.text}")
            except Exception as e:
                st.error(f"Failed to connect to FastAPI: {e}")